### ISSUE TITLE
error when trying to create a session.

### ISSUE THREAD

**Issue by BacchusIX** [unixpickle/cbyge#5]
Sorry, I'm new to all this; what do I need to make this work?  I thought I installed the go language and the git correctly; but I keep getting I keep getting- "syntax error near unexpected token `('" when I try to create a session.

**Comment by unixpickle** [comment]
Could you post the code you are trying to use? Also, cbyge recently changed their backend in an annoying way, so the README doesn't yet document how you do 2FA with this API.

**Comment by unixpickle** [comment]
See this issue https://github.com/unixpickle/cbyge/issues/4

**Comment by unixpickle** [comment]
Going to close issue, but feel free to post any updates / the code snippet I asked for and I can re-open it.
